### ISSUE TITLE
Support user-defined meta tags

### ISSUE THREAD

**Issue by s3ththompson** [tobimori/kirby-seo#23]
I'd like to add [additional tags](https://ogp.me/#type_article) (e.g. `article:published_time` and `article:tag`) when the `og:type` for my page is `article`. 

Ideally I would be able to enumerate these extra tags in the config (and support them by providing data through my `metaDefaults()` page method).

Thanks for the great plugin!

**Comment by s3ththompson** [comment]
(I'd be happy to contribute a PR for this feature if you have an API design in mind.)

**Comment by tobimori** [comment]
Definitely a good addition!

The biggest pain point with user-defined tags is that how they're defined in the head differs from type to type.
An example: Twitter/Browser tags use `name` and `content` attributes, while OG attributes use `property` and `content`.
As a general rule of thumb, we can make tags that include `og` use `property`, and others use `name`. The API has to be flexible enough that you can specify attributes yourself.

Ideally, I want to make the API not differ much from `metaDefaults()` - which currently uses camelCase field names instead of the actual meta tags. We can't potentially map all meta tags to camelCase names, so we'll be mapping the field names to attribute names where the lookup happens.

This is what I'd be thinking about:
```php
<?php

class CustomPage extends \Kirby\Cms\Page
{
  public function metaDefaults(string $lang = null)
  {
    $c = $this->content($lang);

    return [
       // Built-in tags
      'title' => $c->projectTitle()->or($this->title()),
      'og:image' => $c->image(),
      'description' => strip_tags($c->description()),
      'og:description' => strip_tags($c->description()),
      // Custom tags
      'og:article:published_time' => $c->published()->toDate('...'),
      // Array syntax for more control, all items will be output as attributes
      [ 
        'property' => 'og:article:published_time',
        'content' => $c->published()->toDate('...')
      ]
    ];
  }
}
```
