### ISSUE TITLE
seo-preview not valid

### ISSUE THREAD

**Issue by MaluNoPeleke** [tobimori/kirby-seo#29]
After installing this plugin via composer and integrating it in my Kirby instance I see the following information in the SEO tab:
![image](https://github.com/tobimori/kirby-seo/assets/1446541/444e87dd-db26-48a3-8dc4-5b4506755b9d)
I had Meta Knight installed before (but not anymore), if that is important.
![image](https://github.com/tobimori/kirby-seo/assets/1446541/81344d16-f817-4235-a5d6-30786854f265)

**Comment by tobimori** [comment]
To me, it seems like the backend can't find the section type even though the plugin tries to register it. Are there any console errors? I'd assume some part of the PHP getting lost because of that.

It would be great if you can try to nail down the error. I don't think it has anything to do with any third-party plugin, they all seem fine, and I used some of them as well together with kirby-seo.

**Comment by MaluNoPeleke** [comment]
Cannot find an error and in an incognito tab it works as expected. Probably a caching issue.

**Comment by andreasfehn** [comment]
Hi tobimori, I just wanted to say that I had the same problem in a clean installation (kirby-seo-1.0.0-rc.2, Kirby 4.1.0). 
After clearing the cache the error disapeared.
Thanks for your incredible work!
Cheers Andreas
