### ISSUE TITLE
New cascade layer for Open Graph fields to fall back to meta fields

### ISSUE THREAD

**Issue by andreasba** [tobimori/kirby-seo#38]
Hi @tobimori - it's me again :) 

I was wondering what you think of supporting KQL for the OG Description? I found myself pasting the exact same content over and over again and {{ metadescription }} or {{ page.metadescription }} did not work.

Thanks
Andreas

**Comment by tobimori** [comment]
ogDescription should automatically fall back to metaDescription

**Comment by andreasba** [comment]
> ogDescription should automatically fall back to metaDescription (if there is no global ogDescription set)

True - but of the SITE metaDescription not the PAGE metaDescription which makes more sense to me or? :)

**Comment by tobimori** [comment]
It should fall back to the PAGE metaDescription as specified in [options.php](https://github.com/tobimori/kirby-seo/blob/main/config/options.php#L13C1-L14C1). The site ogDescription must be empty as this is how the cascade works:

1. Page fields: The default page blueprint that allows you to specify most options
2. Programmatic content: With Page models you can programmatically set meta tags like you want
3. Inherited fields from parent page: Most fields can be configured to inherit to child pages
4. Site globals: The site blueprint allows you to set global defaults for all pages
*5. Options: The last fallback is defined in the plugin options* -> which is our page metaDescription

**Comment by andreasba** [comment]
Danke, ein klassischer Fall von RTFM bzw. nicht verstanden - ich habe Deine raschen Antworten gar nicht verdient @tobimori  ❤️

**Comment by tobimori** [comment]
Adding KQL support to all fields (if you need the `ogDescription`, you'll most likely also want `metaDescription`, etc.) is a bit hard as KQL doesn't resolve recursively (what happens when a KQL query is in `metaDescription` which is accessed by `ogDescription`, etc.?).

IMO this would also replace programmatic content via models for most people which goes against my mindset of how SEO should be managed:
- setting programmatic defaults is a matter of the developer, so it should be done in code (the editor usually doesn't know the field names, etc)
- setting stuff like the title template is a matter of the editor, because it controls the final appearance on Google search or in the browser

I think it might make sense to add a new cascade layer after programmatic content that resolves `ogTitle` & `ogDescription` to `metaTitle` & `metaDescription`. I'll keep this open for that.
