### ISSUE TITLE
Required fields passing to child's

### ISSUE THREAD

**Issue by Messa1** [tobimori/kirby-seo#45]
Thanks for you plugin.
Is there something i need to set up in config, that it pass parent settings?
Im on Kirby 3.6 and of you plugin i use 0.3.4.

I have a page called jobs and subpages job

http://localhost:8888/jobs
http://localhost:8888/jobs/baufacharbeiter-100-m-w-d

I set on the parent page to pass all field infos to the child's but in my case it is not working.

**Parent:** - Jobs.yml
![Bildschirmfoto 2023-10-18 um 11 22 10](https://github.com/tobimori/kirby-seo/assets/3908658/51fb2383-c032-42ac-9cd1-c49ffd6c55f1)

**Child:** - Job.yml
![Bildschirmfoto 2023-10-18 um 11 22 38](https://github.com/tobimori/kirby-seo/assets/3908658/cd012dfe-8665-4962-9d53-0b27ea33d972)

Also why I can't set something like this up in the site.yml?
For me i would prefer to set up in the site yml for all and defective it on each page - or as example
defective in the parent passing defective to child.

**Site.yml** - missing the possibility - pass to all pages and all childs
![Bildschirmfoto 2023-10-18 um 11 26 17](https://github.com/tobimori/kirby-seo/assets/3908658/48bf18af-1a69-4d22-bf62-44b757dac4e4)

**Comment by tobimori** [comment]
You'll always have to set it to the default value if you add the plugin later on, because Kirby does not have a way to set default fields after a page has been created.
site will automatically pass to all pages and childs, there's no need to "allow" the field for that like on normal pages.

See also: [The Meta Cascade](https://github.com/tobimori/kirby-seo#how-it-works---the-meta-cascade-)

- So what you want should actually be working?

**Comment by tobimori** [comment]
btw, there might be some issues with running Kirby 3.6. It's untested on this version.
I recommend updating to Kirby 3.9.

**Comment by Messa1** [comment]
Sorry my fault im on 3.9.7.

Ah oky that make sense - cause I already have the pages and content and add than your plugin after.
So I need to rework all pages. - But I can copy past it out of the text field - Maybe there for would e a script awesome for doing that job 😄
