### ISSUE TITLE
Default settings button lables

### ISSUE THREAD

**Issue by garethworld** [tobimori/kirby-seo#46]
Great plugin! thank you.

Just wondering if this is bug? would  look nicer if it just said "default" or does there need to default button at all? Could the default state not be inherited ? 

![Screenshot 2023-10-24 at 17 37 52](https://github.com/tobimori/kirby-seo/assets/55981730/67dbef4e-d2ad-4556-baca-22f7e0cfa5ac)

**Comment by tobimori** [comment]
See #40

It's a placeholder that a little javascript snippet replaces so I can correctly inherit the default value as this wouldn't be possible with the programmatic blueprints as I need to know which page the blueprint is used on.

Although I found a way to bypass that so that's probably how I'll fix this
