### ISSUE TITLE
query language in description fields

### ISSUE THREAD

**Issue by jaro-io** [tobimori/kirby-seo#64]
**hey there tobi ✨** 
really cool plugin we have here!

it would be amazing if query language would be enabled for the description fields as well. is this something that could be added in a future version? my blog posts anyway have a `summary` field, so ideally i could just write `{{ page.summary }}` in the `description` field in order to use it.

🙏🏻

**Comment by tobimori** [comment]
I do not plan to make more use of KQL in the plugin. 
It's hard to understand for content editors and should be the responsibility of the developer, and in my opinion therefore belongs in a page model with programmatic content (docs will follow but you can look at other issues for more details).

I should probably remove the title template KQL notice in 1.0 as well - the feature will stay as a side product of allowing `{{ title }}` as replacement.

**Comment by tobimori** [comment]
I asked on [Discord](https://discord.com/channels/525634039965679616/525638772591951882/1198636565652586537) what the community things of this and might reconsider it if I get enough positive feedback.

**Comment by tobimori** [comment]
Another thing to consider: 

Most cases where this would be useful, it's hard to actually use this because of how the cascade works.

In order to set the description to a different field for all article pages, i'd have to set the description with KQL on the parent page and allow inheritation. 

This also means that my blog page uses the same description but probably doesn't have the same field available, and I couldn't set a different one just for the parent/blog page (like with the title template, where I can select whether the current page uses the template or not as a workaround)

**Comment by jaro-io** [comment]
**hey again 🌳** 
thanks for getting back to me so quicky! 

i didnt know about the page model solution. just found it in one of the other [issues](https://github.com/tobimori/kirby-seo/issues/53) like you explained. so that helps a lot, thanks!

and thinking about it again, i do agree regarding `kql`. i am currently working on my personal site, and in this case i wouldn’t mind having the additional options that `kql` enables. but you are totally right, most of the times metadata will be edited by content editors, not the dev. and in this case it can indeed be very confusing.

i am therefore withdrawing my request again haha.
anyway, thanks a lot for looking into this!
🌻 ✨
