### ISSUE TITLE
Sitemap caching

### ISSUE THREAD

**Issue by LuckyRessource** [tobimori/kirby-seo#85]
Hello Tobi,

If you have a lot of pages, retrieving the sitemap.xml can sometimes take more than 15 seconds. There is currently no way to cache the sitemap.xml, as Kirby caching does not work here.

**Comment by tobimori** [comment]
do you have any additional information for me? caching should work and does for my sites:
![sitemap written to cache](https://github.com/tobimori/kirby-seo/assets/29142128/f7d5fbfa-7745-4f7e-b7c4-9535994ecea8)

**Comment by WebMechanic** [comment]
Hello,
we're facing the same issue here. The "sitemap.xml" URL takes ages to appear.
We have +650 txt files in content (and counting) with a variety of different blueprints/templates. 
Many files are used as "modules" to be included/linked to via blocks (similar to your Forms) in the actual articles and pages or serve as "Internal" pages and content only accessible within the Panel (like help pages or file listings).

I added their templates to the `excludeTemplates` of the config:
```js
'excludeTemplates' => [
	'error',
	'form',
	'forms',
	'guide-chapter',
	'listings',
	'intropages',
	'mediathek',
	'category',
	'panel-categories',
	'shared',
	'panel-shared',
	'card',
	'panel-cards',
	'definition',
	'panel-module',
	'module-html',
	'module-data',
	'panel-help',
	'panel-storage',
]
```

How is caching enabled for the sitemap or what may cause this delay? 
I suspect it may evtl. even error out (for whatever other reason) w/o showing an error 'cos I sometimes wait for MINUTES and the "sitemap.xml" page still remains blank

What other information do you need?

Thanks.

**Comment by tobimori** [comment]
The sitemap is cached after full generation using the normal Kirby pages cache.

You can write a custom generator method that uses partial caching if you need so. 

Generally I can't do anything against it running out of time/RAM since Kirby doesn't have a feature for queuing/background tasks. [Please upvote this](https://kirby.nolt.io/207) and maybe we will get it in Kirby 6.

**Comment by WebMechanic** [comment]
I assume the amount of `excludeTemplates` canhave a negative effect? 

anyway upvoted. 
thanks

**Comment by tobimori** [comment]
Kirby will always resolve all pages because of the use of `$site->index()`, in order to filter by template Kirby has to read the file first.

The only way to mitigate this is by moving the generation process to the background and allow it to exceed the 30 sec PHP max execution duration and the RAM limits. This would need queuing/managing the stuff, which should be a Core feature.
